[package]
authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Spacedrive's shared context traits and types"
edition.workspace      = true
license.workspace      = true
name                   = "sd-core-shared-context"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
sd-core-shared-types = { path = "../shared-types" }
sd-prisma            = { path = "../../../crates/prisma" }
sd-sync              = { path = "../../../crates/sync" }

chrono             = { workspace = true, features = ["serde"] }
prisma-client-rust = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
tokio              = { workspace = true, features = ["sync"] }
uuid               = { workspace = true, features = ["serde", "v4"] }
