[package]
authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Spacedrive's custom URI system"
edition.workspace      = true
license.workspace      = true
name                   = "sd-core-custom-uri"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"


[dependencies]
prisma-client-rust = { workspace = true }
sd-prisma          = { path = "../../../crates/prisma" }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
specta             = { workspace = true }
thiserror          = { workspace = true }
uuid               = { workspace = true, features = ["serde", "v4"] }
