[package]
authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Spacedrive's device/node orchestration system"
edition.workspace      = true
license.workspace      = true
name                   = "sd-core-node"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
# Inner Core Sub-crates
sd-core-cloud-services = { path = "../cloud-services" }
sd-core-custom-uri     = { path = "../custom-uri" }
sd-core-job-system     = { path = "../job-system" }
sd-core-library        = { path = "../library" }
sd-core-library-sync   = { path = "../library-sync" }
sd-core-location       = { path = "../location" }
sd-core-location-scan  = { path = "../location-scan" }
sd-core-preferences    = { path = "../preferences" }
sd-core-search         = { path = "../search" }
sd-core-shared-errors  = { path = "../shared-errors" }
sd-core-shared-types   = { path = "../shared-types" }
sd-core-tag            = { path = "../tag" }
sd-core-volume         = { path = "../volume" }

sd-cloud-schema = { workspace = true }
sd-crypto       = { path = "../../../crates/crypto" }
sd-p2p          = { path = "../../../crates/p2p" }
sd-task-system  = { path = "../../../crates/task-system" }
sd-utils        = { path = "../../../crates/utils" }

int-enum   = "0.5"
serde_repr = "0.1.19"

async-channel       = { workspace = true }
async-trait         = { workspace = true }
blake3              = { workspace = true }
chrono              = { workspace = true, features = ["serde"] }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
globset             = { workspace = true }
image               = { workspace = true }
# Update blocked due to API breaking changes
base91             = "0.1.0"
itertools          = { workspace = true }
lending-stream     = { workspace = true }
prisma-client-rust = { workspace = true }
rmp-serde          = { workspace = true }
rmpv               = { workspace = true }
rspc               = { workspace = true }
serde              = { workspace = true, features = ["derive", "rc"] }
serde_json         = { workspace = true }
specta             = { workspace = true }
strum              = { workspace = true, features = ["derive", "phf"] }
strum_macros       = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["fs", "parking_lot", "sync"] }
tokio-stream       = { workspace = true, features = ["fs"] }
tracing            = { workspace = true }
uuid               = { workspace = true, features = ["serde", "v4"] }
webp               = { workspace = true }
whoami             = "1.5.2"
