[package]
name    = "sd-utils"
version = "0.1.0"

edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-prisma = { path = "../prisma" }

# Workspace dependencies
chrono             = { workspace = true }
int-enum           = "0.5"
itertools          = { workspace = true }
prisma-client-rust = { workspace = true }
rmp-serde          = { workspace = true }
rmpv               = { workspace = true }
rspc               = { workspace = true, features = ["unstable"] }
serde              = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
uhlc               = { workspace = true }
uuid               = { workspace = true }
