[package]
name    = "sd-file-actions"
version = "0.1.0"

authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Virtual distributed filesystem engine that powers Spacedrive."
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true


[dependencies]
async-trait         = { workspace = true }
blake3              = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
itertools           = { workspace = true }
rmp-serde           = { workspace = true }
serde               = { workspace = true, features = ["derive"] }
serde_json          = { workspace = true }
specta              = { workspace = true }
thiserror           = { workspace = true }
tracing             = { workspace = true }
uuid                = { workspace = true, features = ["serde", "v4"] }

# core sub-crates
sd-core-file-helper    = { path = "../file-helper" }
sd-core-job-system     = { path = "../job-system" }
sd-core-library-sync   = { path = "../library-sync" }
sd-core-location-scan  = { path = "../location-scan" }
sd-core-prisma-helpers = { path = "../prisma-helpers" }
sd-core-shared-types   = { path = "../shared-types" }

# spacedrive sub-crates
sd-prisma      = { path = "../../../crates/prisma" }
sd-sync        = { path = "../../../crates/sync" }
sd-task-system = { path = "../../../crates/task-system" }
sd-utils       = { path = "../../../crates/utils" }

[dependencies.tokio]
features  = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"]
workspace = true

# Platform-specific dependencies
[target.'cfg(target_os = "macos")'.dependencies]
trash = "5.1"

[target.'cfg(target_os = "linux")'.dependencies]
trash = "5.1"

[target.'cfg(target_os = "windows")'.dependencies]
trash = "5.1"
