[package]
edition.workspace    = true
license.workspace    = true
name                 = "sd-core-location"
repository.workspace = true
version              = "0.1.0"


[features]
default = []
# This feature controls whether the Spacedrive Heavy Lifting contains functionality which requires FFmpeg.
ffmpeg = ["dep:sd-ffmpeg"]

[dependencies]
# Inner Core Sub-crates
sd-core-file-helper    = { path = "../file-helper" }
sd-core-indexer-rules  = { path = "../indexer-rules" }
sd-core-job-errors     = { path = "../job-errors" }
sd-core-job-system     = { path = "../job-system" }
sd-core-library-sync   = { path = "../library-sync" }
sd-core-location-scan  = { path = "../location-scan" }
sd-core-node           = { path = "../node" }
sd-core-prisma-helpers = { path = "../prisma-helpers" }
sd-core-shared-types   = { path = "../shared-types" }

# Spacedrive Sub-crates
sd-ffmpeg         = { path = "../../../crates/ffmpeg", optional = true }
sd-file-ext       = { path = "../../../crates/file-ext" }
sd-images         = { path = "../../../crates/images" }
sd-media-metadata = { path = "../../../crates/media-metadata" }
sd-prisma         = { path = "../../../crates/prisma" }
sd-sync           = { path = "../../../crates/sync" }
sd-task-system    = { path = "../../../crates/task-system" }
sd-utils          = { path = "../../../crates/utils" }

# Workspace dependencies
async-channel = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
futures = { workspace = true }
futures-concurrency = { workspace = true }
globset = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
lending-stream = { workspace = true }
normpath = { workspace = true, features = ["localization"] }
notify = { default-features = false, features = [
	"macos_fsevent"
], git = "https://github.com/notify-rs/notify.git", rev = "c3929ed114" }
prisma-client-rust = { workspace = true }
rmp-serde = { workspace = true }
rmpv = { workspace = true }
rspc = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true }
specta = { workspace = true }
strum = { workspace = true, features = ["derive", "phf"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "parking_lot", "sync"] }
tokio-stream = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }
webp = { workspace = true }


# Specific Heavy Lifting dependencies
static_assertions = "1.1"

[dev-dependencies]
tempfile     = { workspace = true }
tracing-test = { workspace = true }
