[package]
authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Shared types used across Spacedrive core crates"
edition.workspace      = true
license.workspace      = true
name                   = "sd-core-shared-types"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]

# Inner Core Sub-crates
sd-core-library-sync   = { path = "../library-sync" }
sd-core-prisma-helpers = { path = "../prisma-helpers" }
# sd-core-location-scan = { path = "../location-scan" }

chrono             = { workspace = true, features = ["serde"] }
prisma-client-rust = { workspace = true }
sd-prisma          = { path = "../../../crates/prisma" }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
specta             = { workspace = true }
strum              = { workspace = true, features = ["derive", "phf"] }
thiserror          = { workspace = true }
uuid               = { workspace = true, features = ["serde", "v4"] }
