[package]
authors                = ["Spacedrive Technology Inc <support@spacedrive.com>"]
description            = "Shared types used across Spacedrive core crates"
edition.workspace      = true
license.workspace      = true
name                   = "sd-core-shared-types"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
hex = "0.4.3"

# Inner Core Sub-crates
# TO AVOID CYCLIC DEPENDENCIES BE CAREFUL WHEN ADDING LOCAL CRATES HERE
sd-prisma = { path = "../../../crates/prisma" }
sd-utils  = { path = "../../../crates/utils" }

chrono             = { workspace = true, features = ["serde"] }
prisma-client-rust = { workspace = true }
sd-cloud-schema    = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
specta             = { workspace = true }
strum              = { workspace = true, features = ["derive", "phf"] }
strum_macros       = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["fs", "parking_lot", "sync"] }
tracing            = { workspace = true }
uuid               = { workspace = true, features = ["serde", "v4"] }
