name: i18n-check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if translation files exist
        run: |
          if [ ! -f "interface/locales/pl/common.json" ]; then
            echo "Error: Polish translation file not found!"
            exit 1
          fi

      - name: Validate JSON
        run: |
          if ! jq empty interface/locales/pl/common.json; then
            echo "Error: Invalid JSON in Polish translation file!"
            exit 1
          fi
