- name: Import Code Signing Certificates
  if: false  # Pomijamy ten krok
  uses: apple-actions/import-codesign-certs@v2
  with:
    p12-file-base64: ${{ secrets.P12_FILE_BASE64 }}
    p12-password: ${{ secrets.P12_PASSWORD }}